version: "3.8"
services:
  apache:
    image: httpd:2.4-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/usr/local/apache2/htdocs/
    container_name: davidcvwebsite_apache
    working_dir: /usr/local/apache2/htdocs
